[package]
name = "nfswolf-rpcbind"
version.workspace = true
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Portmapper v2 (RFC 1057) and rpcbind v3/v4 (RFC 1833) clients for ONC RPC service discovery."
readme = "README.md"

[dependencies]
nfswolf-xdr = { workspace = true }
nfswolf-rpc = { workspace = true }

[lints]
workspace = true
